language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.2
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - "RAILS_VERSION=4.2.6"
notifications:
  irc:
    channels:
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
