language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.2.7.1"
    - "RAILS_VERSION=5.0.0.1"
notifications:
  irc:
    channels:
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
