language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.0.7.1"
    - "RAILS_VERSION=5.1.6.1"
    - "RAILS_VERSION=5.2.2"
